services: 
  master:
    build:
      context: ./master
      target: spark-master
    command: sbin/start-master.sh
    init: true
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_NO_DAEMONIZE: true
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 8888:8888
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
    networks:
      - spark_network

  worker:
    build:
      context: ./master
      target: spark
    command: sbin/start-worker.sh spark://master:7077
    init: true
    depends_on:
      - master
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_NO_DAEMONIZE: true
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    expose:
      - 7012
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
    networks:
      - spark_network

networks:
  spark_network:
    driver: bridge
