@startuml
title Architecture

actor Client
rectangle "Big Data Cluster" as Cluster {
 node master_node [
    <b>Master
    ----
    Python
    ....
    Spark
    ====
    HDFS
 ]
 node worker_node [
    <b>Worker
    ----
    Spark
    ====
    HDFS
 ]
}

Client <-> master_node
master_node <-> worker_node
@enduml
